linters:
  enable-all: true
  disable:
    - varnamelen
    - depguard
    - godox
    - testpackage
    - exhaustivestruct
    - wsl
    - revive
    - ireturn
    - exhaustruct
    - misspell
    - gomnd
    - paralleltest
    - goerr113 #del mb
    - wrapcheck #del
    - rowserrcheck #del
    - tagliatelle #del
    - nlreturn #del
    - tagalign #del
    - golint #del
    - gci #del
    - gocritic #del
    - stylecheck #del
    - lll #del
    - gofumpt #del
    - godot #del
    - goimports #del
    - funlen #del
