linters:
  enable-all: true
  disable:
    - varnamelen
    - depguard
    - godox
    - testpackage
    - exhaustivestruct
    - wsl
    - revive
    - ireturn
    - exhaustruct
    - misspell
    - gomnd
    - paralleltest
    - goerr113
    - rowserrcheck
    - tagalign
    - gci
    - gofumpt
    - godot
    - goimports
    - funlen #del
    - gofmt #err
    - deadcode #warn
    - golint #warn
    - scopelint #warn
    - interfacer #warn
    - nosnakecase #warn
    - maligned #warn
    - structcheck #warn
    - ifshort #warn
    - varcheck #warn
