linters:
  disable-all: true
  disable:
    - varnamelen
    - depguard
    - godox
    - testpackage
    - exhaustivestruct
    - wsl
    - revive
    - ireturn
    - exhaustruct
    - misspell
    - gomnd


#linters:
#  enable-all: true
#  disable:
#    - varnamelen
#    - depguard
#    - godox
#    - testpackage
#    - exhaustivestruct
#    - wsl
#    - revive
#    - ireturn
#    - exhaustruct
#    - misspell
#    - gomnd
#    - paralleltest
#    - goerr113 #del mb
