linters:
  enable-all: true
  disable:
    - varnamelen
    - depguard
    - godox
    - testpackage
    - exhaustivestruct
    - wsl
    - revive
    - ireturn
    - exhaustruct
    - misspell
    - gomnd
    - paralleltest
    - goerr113
    - rowserrcheck
    - tagalign
    - forbidigo
    - gci
    - gofumpt
    - godot
    - goimports
    - gochecknoglobals
    - errname
    - stylecheck #???
    - funlen #del
    - staticcheck #del
    - sqlclosecheck #del
    - inamedparam #err
    - testifylint #err
    - gofmt #err
    - deadcode #warn
    - golint #warn
    - scopelint #warn
    - interfacer #warn
    - nosnakecase #warn
    - maligned #warn
    - structcheck #warn
    - ifshort #warn
    - varcheck #warn
    - wrapcheck #del!!!
    - whitespace #del!!!
    - nlreturn #del!!!
    - ineffassign #del!!!
    - wastedassign #del!!!
    - lll #del!!!
    - prealloc #del!!!
    - gosec #del!!!
    - gocritic #del!!!
    - dupl #del!!!
