version: "3.9"

services:

  postgres:
    container_name: zuzu-postgres
    image: postgres:latest
    restart: always
    command: 
      - "postgres"
      - "-c"
      - "max_connections=5"
      - "-c"
      - "shared_buffers=100MB"
      - "-c"
      - "effective_cache_size=0.5GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=64MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=1GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata" # storing db files
    env_file:
      - ./.env
    expose:
      - "5432"
    volumes:
      - 'zuzu-db-data:/var/lib/postgresql/data'
      - './build/sql/:/docker-entrypoint-initdb.d/'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M
    networks:
      - zuzu-network

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_CONFIG_SERVER_MODE: "False"
    env_file:
      - ./.env
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
      - "5051:443"
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 100M
    networks:
      - zuzu-network

  zuzu-main:
    env_file:
        - ./.env
    container_name: zuzu-main
    image: MrDjeb/ZuZu:123
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./.env:/docker-zuzu-main/.env
    depends_on:
      - postgres
    networks:
      - zuzu-network

volumes:
  zuzu-db-data:
  pgadmin-data:
  zuzu-db:

networks:
  zuzu-network:
    driver: bridge