version: "3.9"
# to run: docker compose -f "local-docker-compose.yaml" up -d

services:

  zuzu-postgres:
    container_name: zuzu-postgres
    image: postgres:latest # last stable 15.3 for 22/6/2023, equal to latest
    restart: always
    command: #echo "psql -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c "CREATE EXTENSION IF NOT EXISTS "uuid-ossp";"" > start.sh
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
      
    
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata" # storing db files
    env_file:
      - ./.env
    ports:
      - ${POSTGRES_PORT}:5432

    volumes:
      - 'zuzu-db-data:/var/lib/postgresql/data'
      - './build/sql/:/docker-entrypoint-initdb.d/'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 200M
    networks:
      - zuzu-postgres


volumes:
  zuzu-db-data:
  initdb:

networks:
  zuzu-postgres:
    driver: bridge