global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "main"
    metrics_path: /api/metrics
    static_configs:
      - targets: ["0.0.0.0:8096"]

  - job_name: "auth"
    metrics_path: /api/metrics
    static_configs:
      - targets: ["0.0.0.0:8011"]

