name: CI
on:
  push:
    branches:
      - RK2
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v4
      - name: Setup Go
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v3

