definitions:
  models.Cart:
    properties:
      id:
        type: string
      isCurrent:
        type: boolean
      products:
        items:
          $ref: '#/definitions/models.CartProduct'
        type: array
      profileId:
        type: string
    type: object
  models.CartProduct:
    properties:
      description:
        type: string
      id:
        type: string
      img:
        type: string
      name:
        type: string
      price:
        type: integer
      quantity:
        type: integer
      rating:
        type: number
    type: object
  models.Category:
    properties:
      id:
        type: string
      name:
        type: string
      parent:
        type: string
    type: object
  models.Product:
    properties:
      description:
        type: string
      id:
        type: string
      img:
        type: string
      name:
        type: string
      price:
        type: integer
      rating:
        type: number
    type: object
  models.Profile:
    properties:
      description:
        type: string
      id:
        type: string
      img:
        type: string
      login:
        type: string
      password:
        items:
          type: integer
        type: array
    type: object
  models.User:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
  response.Response:
    properties:
      error: {}
      status:
        type: string
    type: object
info:
  contact:
    name: Dima
    url: http://t.me/belozerovmsk
  description: API server for ZuZu.
  title: ZuZu Backend API
paths:
  /api/auth/check_auth:
    get:
      consumes:
      - application/json
      description: Check user auth
      parameters:
      - default: zuzu-t=xxx
        description: Token
        in: header
        name: Cookie
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
      security:
      - AuthKey: []
      summary: CheckAuth
      tags:
      - Auth
  /api/auth/logout:
    get:
      consumes:
      - application/json
      description: Logout from Account
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
      summary: Logout
      tags:
      - Auth
  /api/auth/signin:
    post:
      consumes:
      - application/json
      description: LogIn to Account
      parameters:
      - description: user info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: User profile
          schema:
            $ref: '#/definitions/models.Profile'
        "400":
          description: error messege
          schema:
            $ref: '#/definitions/response.Response'
        "429":
          description: Too Many Requests
      summary: SignIn
      tags:
      - Auth
  /api/auth/signup:
    post:
      consumes:
      - application/json
      description: Create Account
      parameters:
      - description: user info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: User profile
          schema:
            $ref: '#/definitions/models.Profile'
        "400":
          description: error messege
          schema:
            $ref: '#/definitions/response.Response'
        "429":
          description: Too Many Requests
      summary: SignUp
      tags:
      - Auth
  /api/cart/add_product:
    post:
      consumes:
      - application/json
      description: add product to cart or change its number
      parameters:
      - description: product info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.CartProduct'
      produces:
      - application/json
      responses:
        "200":
          description: cart info
          schema:
            $ref: '#/definitions/models.Cart'
        "400":
          description: error message
          schema:
            $ref: '#/definitions/response.Response'
        "401":
          description: Unauthorized
        "429":
          description: Too Many Requests
      summary: AddProduct
      tags:
      - Cart
  /api/cart/delete_product:
    post:
      consumes:
      - application/json
      description: delete product from cart
      parameters:
      - description: product info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.CartProduct'
      produces:
      - application/json
      responses:
        "200":
          description: cart info
          schema:
            $ref: '#/definitions/models.Cart'
        "400":
          description: error message
          schema:
            $ref: '#/definitions/response.Response'
        "401":
          description: Unauthorized
        "429":
          description: Too Many Requests
      summary: DeleteProduct
      tags:
      - Cart
  /api/cart/summary:
    get:
      consumes:
      - application/json
      description: Get cart
      produces:
      - application/json
      responses:
        "200":
          description: Cart info
          schema:
            $ref: '#/definitions/models.Cart'
        "401":
          description: Unauthorized
        "429":
          description: Too Many Requests
      summary: GetCart
      tags:
      - Cart
  /api/category/get_all:
    get:
      consumes:
      - application/json
      description: Get category tree
      produces:
      - application/json
      responses:
        "200":
          description: Category tree
          schema:
            items:
              $ref: '#/definitions/models.Category'
            type: array
        "429":
          description: Too Many Requests
      summary: Category
      tags:
      - Category
  /api/products/{id}:
    get:
      consumes:
      - application/json
      description: Get product
      parameters:
      - description: Product UUID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Product info
          schema:
            $ref: '#/definitions/models.Product'
        "400":
          description: error messege
          schema:
            $ref: '#/definitions/response.Response'
        "429":
          description: Too Many Requests
      summary: Product
      tags:
      - Products
  /api/products/category:
    get:
      consumes:
      - application/json
      description: Get products by category
      parameters:
      - description: Category UUID
        in: query
        name: category_id
        required: true
        type: string
      - description: Skip number of products
        in: query
        name: paging
        type: integer
      - description: Display number of products
        in: query
        name: count
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Product info
          schema:
            items:
              $ref: '#/definitions/models.Product'
            type: array
        "400":
          description: error messege
          schema:
            $ref: '#/definitions/response.Response'
        "429":
          description: Too Many Requests
      summary: Products
      tags:
      - Products
  /api/products/get_all:
    get:
      consumes:
      - application/json
      description: Get products
      parameters:
      - description: Skip number of products
        in: query
        name: paging
        type: integer
      - description: Display number of products
        in: query
        name: count
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Product info
          schema:
            items:
              $ref: '#/definitions/models.Product'
            type: array
        "400":
          description: error messege
          schema:
            $ref: '#/definitions/response.Response'
        "429":
          description: Too Many Requests
      summary: Products
      tags:
      - Products
  /api/user/{id}:
    get:
      consumes:
      - application/json
      description: Get user profile
      parameters:
      - description: Profile UUID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: User profile
          schema:
            $ref: '#/definitions/models.Profile'
        "400":
          description: invalid request
          schema:
            $ref: '#/definitions/response.Response'
        "429":
          description: Too Many Requests
      summary: GetProfile
      tags:
      - User
  /api/user/update-info/{id}:
    get:
      consumes:
      - application/json
      description: Update user data
      parameters:
      - description: Profile UUID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: User profile
          schema:
            $ref: '#/definitions/models.Profile'
        "400":
          description: error messege
          schema:
            $ref: '#/definitions/response.Response'
        "401":
          description: Unauthorized
        "429":
          description: Too Many Requests
      summary: UpdateInfo
      tags:
      - User
  /api/user/update-photo/{id}:
    post:
      consumes:
      - application/json
      description: Update user photo
      parameters:
      - description: Profile UUID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: User profile
          schema:
            $ref: '#/definitions/models.Profile'
        "401":
          description: Unauthorized
        "413":
          description: Request Entity Too Large
        "429":
          description: Too Many Requests
      summary: UpdatePhoto
      tags:
      - User
swagger: "2.0"
