global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ 'localhost:9090' ]
      
  - job_name: "node_exporter"
    metrics_path: /metrics
    static_configs:
      - targets: [ 'node_exporter:9100' ]

  - job_name: "main"
    metrics_path: /api/metrics
    static_configs:
      - targets: [ 'zuzu-main:8096' ]

  - job_name: "auth"
    metrics_path: /api/metrics
    static_configs:
      - targets: ["zuzu-auth:7911"]

  - job_name: "order"
    metrics_path: /api/metrics
    static_configs:
      - targets: [ 'zuzu-order:7912' ]

  - job_name: "products"
    metrics_path: /api/metrics
    static_configs:
      - targets: [ 'zuzu-products:7913' ]



